def tutorial_hitung_campuran():
    print("=" * 80)
    print("  TUTORIAL: Operasi Hitung Campuran")
    print("=" * 80)
    print("\nDalam operasi hitung campuran, urutan pengerjaan sangat penting.")
    print("Aturan yang harus diikuti adalah 'KuKaBaTaKu':")
    print("\n1. KURUNG ()")
    print("   - Kerjakan semua operasi di dalam tanda kurung terlebih dahulu.")
    print("   - Contoh: 10 + (5 - 2) -> Kerjakan (5 - 2) dulu jadi 3.")
    
    print("\n2. KALI (x) dan BAGI (:)")
    print("   - Setelah kurung, kerjakan perkalian dan pembagian.")
    print("   - Keduanya sama kuat, kerjakan dari yang paling kiri.")
    print("   - Contoh: 10 + 4 x 2 -> Kerjakan 4 x 2 dulu jadi 8.")
    print("   - Contoh: 12 : 2 x 3 -> Kerjakan 12 : 2 dulu jadi 6, baru 6 x 3 = 18.")

    print("\n3. TAMBAH (+) dan KURANG (-)")
    print("   - Terakhir, kerjakan pertambahan dan pengurangan.")
    print("   - Keduanya sama kuat, kerjakan dari yang paling kiri.")
    
    print("\n--- CONTOH LENGKAP ---")
    print("Soal: 5 + ( 10 - 2 ) x 3 : 4 - 1")
    print("1. Kurung: 5 + (8) x 3 : 4 - 1")
    print("2. Kali/Bagi (dari kiri):")
    print("   - Kali: 5 + 24 : 4 - 1")
    print("   - Bagi: 5 + 6 - 1")
    print("3. Tambah/Kurang (dari kiri):")
    print("   - Tambah: 11 - 1")
    print("   - Kurang: 10")
    print("\nHasil Akhir: 10")
    print("\n========================================")

def tutorial_matematika_berpola():
    print("=" * 80)
    print("   TUTORIAL: Operasi Matematika Berpola")
    print("=" * 80)
    print("\nSoal jenis ini meminta Anda menemukan pola atau aturan dari")
    print("serangkaian angka, gambar, atau operasi.")
    
    print("\nTips Mencari Pola:")
    print("1. Lihat Selisihnya")
    print("   - Apakah selisih antar angka konstan (tetap)?")
    print("   - Contoh: 2, 5, 8, 11, ... (Polanya selalu ditambah 3)")

    print("\n2. Lihat Rasionya")
    print("   - Apakah angka berikutnya didapat dari perkalian/pembagian?")
    print("   - Contoh: 3, 6, 12, 24, ... (Polanya selalu dikali 2)")

    print("\n3. Pola Bertingkat")
    print("   - Kadang, selisihnya juga membentuk pola baru.")
    print("   - Contoh: 1, 3, 7, 13, 21, ...")
    print("     - Selisih: +2, +4, +6, +8, ... (Selisihnya punya pola +2)")

    print("\n4. Pola Loncat (Fibonacci, dll)")
    print("   - Angka berikutnya adalah hasil operasi dari dua angka sebelumnya.")
    print("   - Contoh: 1, 1, 2, 3, 5, 8, ... (Pola Fibonacci, 1+1=2, 1+2=3, dst.)")
    
    print("\n--- CONTOH LENGKAP ---")
    print("Soal: Tentukan angka berikutnya dari 5, 6, 8, 11, ...")
    print("Analisis:")
    print(" - dari 5 ke 6 -> selisih +1")
    print(" - dari 6 ke 8 -> selisih +2")
    print(" - dari 8 ke 11 -> selisih +3")
    print("Pola selisihnya adalah +1, +2, +3. Maka selisih berikutnya adalah +4.")
    print("Jawaban: 11 + 4 = 15")
    print("\n========================================")

def tutorial_barisan_deret():
    print("=" * 80)
    print("    TUTORIAL: Matematika Barisan & Deret")
    print("=" * 80)
    print("\nBarisan adalah urutan bilangan dengan pola tertentu.")
    print("Deret adalah jumlah dari suku-suku barisan tersebut.")

    print("\n--- 1. BARISAN ARITMETIKA ---")
    print("Pola: Beda (selisih) antar suku selalu SAMA (konstan).")
    print("Contoh: 4, 7, 10, 13, ... (Bedanya selalu +3)")
    print(" - Suku pertama (a) = 4")
    print(" - Beda (b) = 3")
    print("\nRumus Suku ke-n (Un):")
    print("   Un = a + (n - 1) * b")
    print("   Contoh: Suku ke-10 (U10) = 4 + (10 - 1) * 3 = 4 + 9 * 3 = 4 + 27 = 31")
    
    print("\nRumus Jumlah n Suku (Sn) / Deret Aritmetika:")
    print("   Sn = n/2 * (a + Un)   ATAU   Sn = n/2 * (2a + (n - 1) * b)")
    print("   Contoh: Jumlah 10 suku pertama (S10) = 10/2 * (4 + 31) = 5 * 35 = 175")

    print("\n--- 2. BARISAN GEOMETRI ---")
    print("Pola: Rasio (perbandingan) antar suku selalu SAMA (konstan).")
    print("Contoh: 2, 6, 18, 54, ... (Rasionya selalu x3)")
    print(" - Suku pertama (a) = 2")
    print(" - Rasio (r) = 3")
    
    print("\nRumus Suku ke-n (Un):")
    print("   Un = a * r^(n-1)   (r pangkat n-1)")
    print("   Contoh: Suku ke-5 (U5) = 2 * 3^(5-1) = 2 * 3^4 = 2 * 81 = 162")

    print("\nRumus Jumlah n Suku (Sn) / Deret Geometri:")
    print("   Sn = a * (r^n - 1) / (r - 1)   (jika r > 1)")
    print("   Contoh: Jumlah 5 suku (S5) = 2 * (3^5 - 1) / (3 - 1) = 2 * (243 - 1) / 2 = 242")
    print("\n========================================")